### ISSUE TITLE
Waveshare v4 icon rendering issues

### ISSUE THREAD

**Issue by cyberartemio** [cyberartemio/wof-pwnagotchi-plugin#14]
Apparently, on Waveshare v3/v4 screens (and probably other screens) the icon is not rendering properly resulting in only 2 dots rendered on screen (both on display and also on the web ui).

**EDIT**: on v3 screens the icon renders fine. Tried to run with inverted colors also.

*Bug reported by [sn0ren](https://www.youtube.com/@sn0ren)*

![proof](https://github.com/cyberartemio/wof-pwnagotchi-plugin/assets/156206062/627cb4b9-2c82-4454-a46e-1e4e29c8098f)

**Comment by cyberartemio** [comment]
Seems like the plugin was installed using `pwnagotchi plugins` command and it doesn't download `wof_assets` directory. There are still some issues with the icon rendering on v4 displays but at least it's showing

**Comment by cyberartemio** [comment]
The icon still doesn't render right. Should rewrite the Icon Widget class

**Comment by RoiArthurB** [comment]
Same issue with "waveshare_3" after copy-pasting installation procedure from READMEs

![image](https://github.com/cyberartemio/wof-pwnagotchi-plugin/assets/16764085/14db6a5c-9249-4331-a6e9-017857d0d38d)

**Comment by cyberartemio** [comment]
I'm releasing v1.3. Try to update it and let me know if you still have the problem. Make sure to redownload the `wof_assets` directory.

> Same issue with "waveshare_3" after copy-pasting installation procedure from READMEs
> 
> ![image](https://private-user-images.githubusercontent.com/16764085/319446100-14db6a5c-9249-4331-a6e9-017857d0d38d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjM5NzIsIm5iZiI6MTcxMjIyMzY3MiwicGF0aCI6Ii8xNjc2NDA4NS8zMTk0NDYxMDAtMTRkYjZhNWMtOTI0OS00MzMxLWE2ZTktMDE3ODU3ZDBkMzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA5NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZThlODJkOGY0YmE2NWM5ZGJmZGI4N2YwMzA4Mzc2ZGNlYTdkZTE1MGYxM2YyMDYyZDI2M2ZkYjY5Y2FlNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_YRZ1_3_Uu4X5AbHpgc105W5K9Fob-cAjDBmmdT9Uc)
