### ISSUE TITLE
Bluetooth tether + WOF?

### ISSUE THREAD

**Issue by JD-2006** [cyberartemio/wof-pwnagotchi-plugin#15]
Would this work with pwnagotchi's bluetooth tether plugin active?

**Comment by cyberartemio** [comment]
Yes, I've tested on mine and it's working fine. Also other people on Discord reported the same.

**Comment by cyberartemio** [comment]
Closing this as done. If you encounter in some connection issues, open another Github issue specifying the problem. If you have further questions, feel free to reopen this
