### ISSUE TITLE
BT Tether + WOF = [ERROR] org.bluez.Error.InProgress: Operation already in progress

### ISSUE THREAD

**Issue by lukasvolcik** [cyberartemio/wof-pwnagotchi-plugin#19]
Title says it all... when I install and enable WOF service I get **[ERROR] org.bluez.Error.InProgress: Operation already in progress** when my device is trying to connect to my phone. Usually after boot it connects and then disconnects after a while or it won't reconnect back... but often won't connect at all (I think depending on the last state I was in before rebooting) 

I used (sudo su) **systemctl disable wof** and then it reconnected even without a reboot... And even when I use WOF UI to enable/disable wof it seems to be working correctly with bt tethering and everything.... 

So skipping the step to enable wof service, or adding disable line at the end of your installation process **is the solution**

**Comment by vollukas** [comment]
(Used wrong account) 
It didn't solve the issue :( and not sure if error really is connected to WOF...

**Comment by lukasvolcik** [comment]
Not related, just did a fresh install, tried bt-tethering, and got the same error after losing a connection and trying to reconnect without WOF being touched..
